# Generated by Django 4.1.7 on 2023-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('fname', models.CharField(max_length=30)),
                ('fdesc', models.CharField(max_length=150)),
                ('fprice', models.IntegerField()),
            ],
        ),
    ]
