# Generated by Django 4.1.7 on 2023-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='fid',
        ),
        migrations.AddField(
            model_name='food',
            name='fimg',
            field=models.CharField(default='https://media.istockphoto.com/id/1137255480/vector/coming-soon-sign.jpg?s=612x612&w=0&k=20&c=ylVtvAGDo4XDBhEiktRkawpm8UDRryPaW3hNDknpxBw=', max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='fdesc',
            field=models.CharField(max_length=300),
        ),
    ]
