# Generated by Django 4.1.7 on 2023-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_remove_food_fid_food_fimg_alter_food_fdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fimg',
            field=models.CharField(max_length=300),
        ),
    ]
